function plotRobot(robot, goal)
            x = robot.position(1);
            y = robot.position(2);
            theta = robot.position(3);

            plotBody(goal, 'y');
            plotBody(robot, 'r');

            hold on;

            plot( ...
                robot.positionHistory(1,:), ...
                robot.positionHistory(2,:), ...
                'b', 'lineWidth', 2 ...
            );

            plot( ...
                x, y, ...
                'or', 'linewidth', 2, ...
                'markersize', 15 ...
            );

            plot( ...
                [x, x + 0.1*cos(theta)], ...
                [y, y + 0.1*sin(theta)], ...
                'k', 'linewidth', 2 ...
            );

            plot( ...
                [x, x + robot.wheelAxis/2*cos(theta + pi/2)], ...
                [y, y + robot.wheelAxis/2*sin(theta + pi/2)], ...
                'k', 'linewidth', 2 ...
            );

            plot( ...
                [x, x + robot.wheelAxis/2*cos(theta - pi/2)], ...
                [y, y + robot.wheelAxis/2*sin(theta - pi/2)], ...
                'k', 'linewidth', 2 ...
            );

            hold off;
            axis equal;
            xlabel('x [m]');
            ylabel('y [m]');
            title(sprintf( ...
                'v = %.4f m/s  |  w = %.4f rad/s', ...
                robot.velocity, ...
                robot.angularVelocity ...
            ));
            grid on;
            drawnow
        end