function plotRobot(robot, goal, obstacles)

            plotBody(goal, 'y');
            plotBody(robot, 'r');

            hold on;

            for ind = 1:length(obstacles)
                plotObstacle(obstacles(ind));
            end

            plotCollisionAndInfluenceZones(robot)

            plot( ...
                robot.positionHistory(1,:), ...
                robot.positionHistory(2,:), ...
                'b', 'lineWidth', 2 ...
            );

%             plot( ...
%                 robot.position(1), ...
%                 robot.position(2), ...
%                 'ok', 'linewidth', 2, ...
%                 'markersize', 15 ...
%             );

            hold off;
            axis equal;
            xlabel('x [m]');
            ylabel('y [m]');
            title(sprintf( ...
                'v = %.4f m/s  |  w = %.4f rad/s', ...
                robot.velocity, ...
                robot.angularVelocity ...
            ));
            grid on;
            drawnow
        end