function plotBody(robot, color)

    x = robot.position(1);
    y = robot.position(2);
    theta = robot.position(3);

    fill(robot.body.center(1,:), robot.body.center(2,:), color)
            
    hold on;

    fill( ...
        robot.body.leftWheel(1,:), ...
        robot.body.leftWheel(2,:), ...
        'k' ...
    );

    fill( ...
        robot.body.rightWheel(1,:), ...
        robot.body.rightWheel(2,:), ...
        'k' ...
    );

    plot( ...
        [x, x + 0.2*cos(theta)], ...
        [y, y + 0.2*sin(theta)], ...
        'k', 'linewidth', 2 ...
    );

    plot( ...
        [x, x + robot.wheelAxis/1*cos(theta + pi/2)], ...
        [y, y + robot.wheelAxis/1*sin(theta + pi/2)], ...
        'k', 'linewidth', 2 ...
    );

    plot( ...
        [x, x + robot.wheelAxis/1*cos(theta - pi/2)], ...
        [y, y + robot.wheelAxis/1*sin(theta - pi/2)], ...
        'k', 'linewidth', 2 ...
    );

    thetaArray = 0:2:360;
    plot( ...
        x + robot.body.collisionZone * cosd(thetaArray), ...
        y + robot.body.collisionZone * sind(thetaArray), ...
        'r', 'linewidth', 3 ...
    );

end