function plotCollisionAndInfluenceZones(robot)
    
    x = robot.position(1);
    y = robot.position(2);
    thetaArray = 0:2:360;

    plot( ...
        x + robot.collisionZone * cosd(thetaArray), ...
        y + robot.collisionZone * sind(thetaArray), ...
        'r', 'linewidth', 3 ...
    );

    plot( ...
        x + robot.influenceZone * cosd(thetaArray), ...
        y + robot.influenceZone * sind(thetaArray), ...
        'g', 'linewidth', 3 ...
    )
end